config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/", to: "home#index"

  resources :patients do
    member do
      put :sync
    end
  end

  resources :contacts

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  DEFAULT_AVATAR_URL="https://robohash.org/quitotamnon.png?size=300x300&set=set1"

  belongs_to :patient, optional: true

  validates :first_name, presence: true
  validates :last_name, presence: true

  def create_patient!(attributes = {})
    super({
      first_name: first_name,
      last_name: last_name,
      avatar_url: DEFAULT_AVATAR_URL,
    }.merge(attributes))
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_one :contact, autosave: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.includes(:patient).all.order(:first_name, :last_name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  rescue_from PatientSyncService::SyncError, with: :flash_sync_error
  
  def index
    @patients = Patient.all.order(:first_name, :last_name)
  end

  def create
    patient = Contact.find(params[:contact_id]).create_patient!

    flash[:info] = "Created patient '#{patient.first_name} #{patient.last_name}' with Sicklie"

    redirect_to controller: :contacts, action: :index
  end

  def sync
    @patient = Patient.find(params[:id])

    PatientSyncService.new(@patient).sync

    flash[:info] = "Synced patient '#{@patient.first_name} #{@patient.last_name}' with Sicklie"
    redirect_to action: :index
  end

  private

  def flash_sync_error(error)
    flash[:danger] = error.message
    redirect_to action: :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/index.html.erb
<h2 class="text-lg sm:text-2xl font-extrabold">Contact Directory</h2>

<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 my-4 justify-items-center">
  <% @contacts.each do |contact| %>
    <% if contact.patient %>
      <%= render PatientCardComponent.new(contact.patient) %>
    <% else %>
      <%= render ContactCardComponent.new(contact) %>
    <% end %>
  <% end %>
</div>

app/views/home/index.html.erb
<h2 class="mt-3 mb-2 text-xl font-semibold">Welcome to Somersault!</h2>
<p class="mb-3"> As an early-stage healthcare startup, our first engineering task is to build a Rails app that manages our patients.</p>

<p class="mb-3">
  We already have a functional 
  <a href="<%= patients_path %>" class="font-medium text-blue-600 underline">patients page</a>
  that shows the patients in our own database as a list of "card" elements.
</p>

<p class="mb-3">Because we don't have time to build everything ourselves, we use a third-party service called Sicklie to manage the health records (EHR) and appointments for our patients.</p>

<p class="mb-3">Our integration with Sicklie is very basic at the moment - we have a button for each patient on our patients page that we manually click to "sync" that patient with Sicklie. 
When we "sync", we call the Sicklie API to create a new patient record in Sicklie if it doesn't exist yet, or updates their record if it already does.</p>

<h2 class="mb-2 text-lg font-semibold">We have two high-priority tasks for you:</h2>
<ol class="space-y-1 list-decimal list-inside mb-3">
  <li class="mb-2">
    Sicklie hasn't been very reliable so far. At times, it seems like they're just sending us random responses back instead of doing what we ask. Because of this, when we click the "sync" button it's very important that we can see in the UI if the request was successful. When it's not successful, we need to show anything they tell us so we have a better chance of fixing the problem.
    <ul class="mt-2 pl-5 space-y-1 list-disc list-inside">
      <li>Add success and error reporting for the "sync" button.</li>
    </ul>
  </li>
  <li>
    The business is growing and we want our app to manage not only current patients, but prospective patients. The business calls a prospective patient a "Contact".
    We'll need a new model to represent a Contact, and a new page with the same grid layout as the patients page, but listing all the Contact records instead.
    <ul class="mt-2 pl-5 space-y-1 list-disc list-inside">
      <li>A Contact has a first name and last name, similar to a patient. This is the only info we need to show on the card.</li>
      <li>
        Within a Contact card, we will need a button that lets the Contact become a Patient (that is, create an associated Patient record in our database).
        When creating the Patient, you can just populate the avatar_url with a hard-coded value (e.g. "https://robohash.org/quitotamnon.png?size=300x300&set=set1").
        </li>
      <li>Once a Contact has an associated Patient, we will want to render the Contact card exactly as if it were a Patient instead (including the working Sync button).
        <p>So the Contacts grid could look something like this:</p>
        <%= image_tag "contacts-page-example.png" %>
        <p>(Georgianna and Clint are both Contacts, but only Clint has become a Patient).</p>
      </li>
    </ul>
  </li>
</ol>

<h2 class="my-2 text-lg font-semibold">Things to keep in mind</h2>
<ul class="my-2 space-y-1 list-disc list-inside">
  <li>It's fair game to add new files. Any existing file can be changed unless it specifically says otherwise.</li>
  <li>There are no right or wrong solutions as long as the requirements are met - but we do like to be able to explain our decisions.</li>
  <li>We do have a very minimal rspec test suite that needs to stay passing. More coverage is always a bonus, especially for new code.</li>
  <li>Good luck!</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Somersault Company Portal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-4 px-4">
      <div class="flex items-center text-green-800">
        <svg class="w-6 h-6 mr-2 bg-green-800 text-white p-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 20">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 1v5h-5M2 19v-5h5m10-4a8 8 0 0 1-14.947 3.97M1 10a8 8 0 0 1 14.947-3.97"/>
        </svg>
        <h1 class="font-bold text-2xl sm:text-4xl whitespace-nowrap">Somersault Healthcare</h1>
      </div>

      <% flash.each do |key, value| %>
        <% 
        flash_classes = case key
          when "success"
            "text-green-800 border-green-300 bg-green-50"        
          when "info"
            "text-blue-800 border-blue-300 rounded-lg bg-blue-50"
          when "warning"
            "text-yellow-800 border-yellow-300 bg-yellow-50"          
          when "danger"
            "text-red-800 border-red-300 bg-red-50"
          else
            ""        
          end
        %>
        <div class="flex items-center p-4 my-4 text-sm border rounded-lg <%= flash_classes %>" role="alert">
          <svg class="flex-shrink-0 inline w-4 h-4 mr-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
          </svg>
          <div><%= value %></div>
        </div>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/patients/index.html.erb
<h2 class="text-lg sm:text-2xl font-extrabold">Patient Directory</h2>

<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 my-4 justify-items-center">
  <% @patients.each do |patient| %>
    <%= render PatientCardComponent.new(patient) %>
  <% end %>
</div>